trigger:
  - main

stages:
  - stage:
    displayName: Example Stage 1
     jobs:
       - job: Stage1 Job1 
         displayName: Stage1 Job1
         steps:
           - bash: echo Stage1 Job1 task1
             displayName: Stage1 Job1 task1
           - bash: Stage1 Job1 task2
             displayName: Stage1 Job1 task1
        - job: Stage1 Job2
          displayName: Stage1 Job2
          dependsOn: Stage1 Job1
          steps:
            - bash: echo Stage1 Job2 task1
              displayName: Stage1 Job2 task1

    - stage:
      displayName: Example Stage 2
      dependsOn: Example Stage 1
      jobs:
        - job:
          displayName: Stage2 Job1
          steps:
            - bash: echo Stage2 Job1 task1
              displayName: Stage2 Job2 task1
        - job:
          displayName: Stage2 Job2
          dependsOn: Stage2 Job1
          steps:
            - bash: echo Stage2 Job2 task1
              displayName: Stage2 Job2 task1
            

